name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    if: "contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          working-directory: docs
          bundler-cache: true
      - name: Index changed posts
        working-directory: docs
        run: |
          git diff --name-only HEAD^ > changes.txt
          cat changes.txt
          bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
